// Code generated by MockGen. DO NOT EDIT.
// Source: moralisnft.go

// Package moralisnft is a generated GoMock package.
package moralisnft

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMoralisNFT is a mock of MoralisNFT interface.
type MockMoralisNFT struct {
	ctrl     *gomock.Controller
	recorder *MockMoralisNFTMockRecorder
}

// MockMoralisNFTMockRecorder is the mock recorder for MockMoralisNFT.
type MockMoralisNFTMockRecorder struct {
	mock *MockMoralisNFT
}

// NewMockMoralisNFT creates a new mock instance.
func NewMockMoralisNFT(ctrl *gomock.Controller) *MockMoralisNFT {
	mock := &MockMoralisNFT{ctrl: ctrl}
	mock.recorder = &MockMoralisNFTMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoralisNFT) EXPECT() *MockMoralisNFTMockRecorder {
	return m.recorder
}

// GetList mocks base method.
func (m *MockMoralisNFT) GetList(addressWallet, addressNFT, chain, format, cursor string, limit int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", addressWallet, addressNFT, chain, format, cursor, limit)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockMoralisNFTMockRecorder) GetList(addressWallet, addressNFT, chain, format, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockMoralisNFT)(nil).GetList), addressWallet, addressNFT, chain, format, cursor, limit)
}

// GetWalletBalance mocks base method.
func (m *MockMoralisNFT) GetWalletBalance(addressWallet, chain, tokenAddress string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletBalance", addressWallet, chain, tokenAddress)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletBalance indicates an expected call of GetWalletBalance.
func (mr *MockMoralisNFTMockRecorder) GetWalletBalance(addressWallet, chain, tokenAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletBalance", reflect.TypeOf((*MockMoralisNFT)(nil).GetWalletBalance), addressWallet, chain, tokenAddress)
}
